ALTER TABLE palisade_signal ADD COLUMN IF NOT EXISTS entry_price DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE palisade_signal ADD COLUMN IF NOT EXISTS target_price DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE palisade_signal ADD COLUMN IF NOT EXISTS min_exit_price DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE palisade_signal ADD COLUMN IF NOT EXISTS net_profit DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE palisade_signal ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE palisade_signal ADD COLUMN IF NOT EXISTS invalidation_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE palisade_signal ADD COLUMN IF NOT EXISTS valid_until TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE palisade_signal ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
