ALTER TABLE paper_trade
    ADD COLUMN IF NOT EXISTS entry_mode TEXT NOT NULL DEFAULT 'LIMIT_AT_SUPPORT',
    ADD COLUMN IF NOT EXISTS support_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS expected_net_profit DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE palisade_signal
    ADD COLUMN IF NOT EXISTS support_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS strategy_version INT NOT NULL DEFAULT 2;
